# arquivo 2
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
print(ADHFDFFDFVFVFHFHFVF)
